### PR TITLE
chore: Cleanup actors desriptions

### PR DESCRIPTION
**Pull request by Jkuzz**
Mostly whitespace changes to descriptions, with an occasional word added.

### CODE REVIEW

**Review by jirispilka — APPROVED** [review]
Suggestion: maybe we should put back the double lines just for `Get list of Actors` and `Create version`. The text is collapsed into a single paragraph and it is long.

**Comment by Jkuzz** [comment]
Should we leave this until #75 ?

**Comment by jirispilka** [comment]
What do u think @netmilk ?
Maybe we should merge it and deal with the formatting later.

**Comment by netmilk** [comment]
Unfortunately, I think the descriptions need to be redone as YAML literal blocks (`|`)  instead of[ folded blocks](https://redocly.com/docs/yaml/blocks-and-flows#folded-blocks) to support properly functioning Markdown. I've done the conversion programmatically and I think it fixed most of the issues, except the already manually edited ones. Let's review together with the content before launch.

New:
```
- description: |
   # some mardown header here
```
Old:
```
- description: >-
   # some mardown header here
```

**Pull request closed without merging**
